#! /bin/sh

set -e;

cpp="$1";
shift;
while [ $# -gt 0 ];
do
	case "$1" in
	-*)
		cpp="$cpp $1";
		;;
	*)
		break;
		;;
	esac
	shift;
done

for csrc;
do
	sedcsrc=`echo "$csrc" | sed -e 's/\\./\\\\./g'`;
	echo "${csrc}:" `$cpp "$csrc" \
		| sed -n \
			-e '/^#  *[0-9][0-9]*  *"/!d;' \
			-e 's/^.*"\(.*\)".*$/\1/;' \
			-e '/^\//d;' \
			-e '/^'"${sedcsrc}"'$/d;' \
			-e 'p;' \
		| sort \
		| uniq`;
done

exit 0;
